name: Pytest & Flake8 Control Push
on: push
env:
  DAY_OF_WEEK: Lundi
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      GREETING: "Salut"
  qa:
    name: Check tests and code quality
    runs-on: ubuntu-latest
    steps:
      steps:
  - name: "Dites Salut Mona nous sommes lundi"
    run: echo "$GREETING $FIRST_NAME. Nous sommes $DAY_OF_WEEK!"
    env:
      FIRST_NAME: Mona
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install pytest flake8
      - name: Run pytest
        run: pytest
      - name: Run flake8
        run: flake8
